# Generated by Django 5.1.1 on 2024-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date",
            field=models.CharField(max_length=255),
        ),
    ]
